#!/usr/bin/env bash
# Install GrotFoxy as a background service on a Linux host.
#
#   ./scripts/install-linux.sh              # bind 0.0.0.0:8787
#   PORT=9000 ./scripts/install-linux.sh    # different port
#   BIND=127.0.0.1 ./scripts/install-linux.sh
#
# On a systemd host this installs a hardened unit that starts at boot (sudo is
# required for that step only). Anywhere else — a container, WSL without
# systemd, a minimal VM — it falls back to a supervised background process.
#
# Re-running is safe.

set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_NAME="grotfoxy"
PORT="${PORT:-8787}"
BIND="${BIND:-0.0.0.0}"
RUN_USER="${SUDO_USER:-$(id -un)}"
RUN_HOME="$(getent passwd "$RUN_USER" | cut -d: -f6)"
STATE_DIR="${GROTFOXY_STATE_DIR:-$RUN_HOME/.grotfoxy}"

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
ok() { printf '    \033[32m✓ %s\033[0m\n' "$1"; }
warn() { printf '    \033[33m! %s\033[0m\n' "$1"; }
die() { printf '    \033[31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

as_user() {
  if [ "$(id -un)" = "$RUN_USER" ]; then "$@"; else sudo -u "$RUN_USER" "$@"; fi
}

has_systemd() { [ -d /run/systemd/system ]; }

# --- 1. Node ------------------------------------------------------------------

step "Checking Node.js"
command -v node >/dev/null 2>&1 || die "Node.js is not installed. Install Node 22 LTS or newer."
NODE_VERSION="$(node --version | sed 's/^v//')"
NODE_MAJOR="${NODE_VERSION%%.*}"
NODE_MINOR="$(echo "$NODE_VERSION" | cut -d. -f2)"
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 5 ]; }; then
  die "Node $NODE_VERSION is too old; GrotFoxy needs 22.5.0+ for the built-in SQLite module."
fi
ok "node $NODE_VERSION"

# --- 2. State directory -------------------------------------------------------

# Deliberately outside the checkout: `data/` is gitignored, so leaving the
# database in the repo means `git clean -xdf` silently destroys every bot,
# transcript and API key.
step "Preparing the state directory"
as_user mkdir -p "$STATE_DIR/data" "$STATE_DIR/workspace"
mkdir -p "$APP_ROOT/logs"

stamp="$(date +%Y%m%d%H%M%S)"
for legacy in data workspace; do
  src="$APP_ROOT/$legacy"
  dest="$STATE_DIR/$legacy"
  if [ -d "$src" ] && [ -n "$(ls -A "$src" 2>/dev/null)" ] && [ -z "$(ls -A "$dest" 2>/dev/null)" ]; then
    cp -a "$src/." "$dest/"
    # The backup goes outside the repo too. It contains master.key, so leaving
    # it in a checkout is how a private key ends up in a public commit.
    as_user mkdir -p "$STATE_DIR/backups"
    mv "$src" "$STATE_DIR/backups/$legacy-$stamp"
    ok "migrated $legacy/ out of the checkout (backup in $STATE_DIR/backups)"
  fi
done
ok "state lives in $STATE_DIR"

# --- 3. Configuration ---------------------------------------------------------

step "Writing configuration"
if [ -f "$APP_ROOT/.env" ]; then
  ok ".env already exists — leaving it alone"
else
  as_user tee "$APP_ROOT/.env" > /dev/null <<EOF
# GrotFoxy configuration — generated by install-linux.sh
GROTFOXY_HOST=$BIND
GROTFOXY_PORT=$PORT

# Encrypts stored API keys. Changing it makes existing keys unreadable.
GROTFOXY_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

GROTFOXY_DATA_DIR=$STATE_DIR/data
GROTFOXY_WORKSPACE_DIR=$STATE_DIR/workspace
GROTFOXY_LOG_LEVEL=info
EOF
  chmod 600 "$APP_ROOT/.env"
  ok "created $APP_ROOT/.env"
fi
chown -R "$RUN_USER" "$STATE_DIR" "$APP_ROOT/logs" 2>/dev/null || true

# --- 4. Supervisor ------------------------------------------------------------

chmod +x "$APP_ROOT/scripts/supervise.sh" "$APP_ROOT/scripts/service.sh"

if has_systemd; then
  step "Installing the systemd unit"
  [ "$(id -u)" -eq 0 ] || die "systemd detected — re-run with sudo so the unit can be installed."

  cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=GrotFoxy — self-hosted AI teammates
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$APP_ROOT
ExecStart=$(command -v node) --experimental-sqlite --no-warnings $APP_ROOT/src/index.js
Restart=always
RestartSec=10
StandardOutput=append:$APP_ROOT/logs/grotfoxy.log
StandardError=append:$APP_ROOT/logs/grotfoxy.log

# The teammates only ever need their own tree and their state directory.
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths=$APP_ROOT $STATE_DIR

[Install]
WantedBy=multi-user.target
EOF
  ok "unit written to /etc/systemd/system/${SERVICE_NAME}.service"

  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null
  systemctl restart "$SERVICE_NAME"
  ok "service enabled and started (it will come back after a reboot)"
else
  step "No systemd on this host — using the fallback supervisor"
  warn "PID 1 is $(ps -p 1 -o comm= 2>/dev/null); GrotFoxy cannot be started at boot here."
  warn "Run 'scripts/service.sh start' after a restart, or install on a systemd host for boot persistence."
  as_user "$APP_ROOT/scripts/service.sh" restart >/dev/null 2>&1 || as_user "$APP_ROOT/scripts/service.sh" start
  ok "supervisor running (restarts GrotFoxy if it ever exits)"
fi

# --- 5. Firewall --------------------------------------------------------------

if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
  sudo ufw allow "$PORT/tcp" >/dev/null && ok "ufw now allows TCP $PORT"
fi

# --- 6. Wait for it to answer -------------------------------------------------

step "Waiting for GrotFoxy to answer"
ready=""
for _ in $(seq 1 40); do
  if curl -fsS "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1; then ready=1; break; fi
  sleep 1
done
[ -n "$ready" ] || die "no response on port $PORT — check $APP_ROOT/logs/grotfoxy.log"
ok "GrotFoxy is responding"

echo
echo "  GrotFoxy is installed."
echo
echo "  On this machine:  http://localhost:$PORT"
for address in $(hostname -I 2>/dev/null || true); do
  echo "  From your phone:  http://$address:$PORT"
done
echo
echo "  State:   $STATE_DIR   (back this up)"
echo "  Logs:    $APP_ROOT/scripts/service.sh logs"
echo "  Control: $APP_ROOT/scripts/service.sh {start|stop|restart|status}"
echo
