#!/usr/bin/env bash
# Install GrotFoxy as a systemd service, for a Den Computer running Linux.
#
#   sudo ./scripts/install-linux.sh            # bind 0.0.0.0:8787
#   sudo PORT=9000 ./scripts/install-linux.sh  # different port
#
# Re-running is safe.

set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_NAME="grotfoxy"
PORT="${PORT:-8787}"
BIND="${BIND:-0.0.0.0}"
RUN_USER="${SUDO_USER:-$(id -un)}"

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
ok() { printf '    \033[32m✓ %s\033[0m\n' "$1"; }
die() { printf '    \033[31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run with sudo so the systemd unit can be installed."

step "Checking Node.js"
command -v node >/dev/null 2>&1 || die "Node.js is not installed. Install Node 22 LTS or newer."
NODE_VERSION="$(node --version | sed 's/^v//')"
NODE_MAJOR="${NODE_VERSION%%.*}"
NODE_MINOR="$(echo "$NODE_VERSION" | cut -d. -f2)"
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 5 ]; }; then
  die "Node $NODE_VERSION is too old; GrotFoxy needs 22.5.0+ for the built-in SQLite module."
fi
ok "node $NODE_VERSION"

step "Writing configuration"
if [ -f "$APP_ROOT/.env" ]; then
  ok ".env already exists — leaving it alone"
else
  cat > "$APP_ROOT/.env" <<EOF
# GrotFoxy configuration — generated by install-linux.sh
GROTFOXY_HOST=$BIND
GROTFOXY_PORT=$PORT

# Encrypts stored API keys. Changing it makes existing keys unreadable.
GROTFOXY_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

GROTFOXY_LOG_LEVEL=info
EOF
  chmod 600 "$APP_ROOT/.env"
  ok "created $APP_ROOT/.env"
fi

mkdir -p "$APP_ROOT/data" "$APP_ROOT/workspace" "$APP_ROOT/logs"
chown -R "$RUN_USER" "$APP_ROOT/data" "$APP_ROOT/workspace" "$APP_ROOT/logs"
ok "data, workspace and logs folders ready"

step "Installing the systemd unit"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=GrotFoxy — self-hosted AI teammates
Documentation=https://github.com/robertpfox/cursor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$APP_ROOT
ExecStart=$(command -v node) --experimental-sqlite --no-warnings $APP_ROOT/src/index.js
Restart=always
RestartSec=10
StandardOutput=append:$APP_ROOT/logs/grotfoxy.log
StandardError=append:$APP_ROOT/logs/grotfoxy.log

# The teammates only ever need their own tree.
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths=$APP_ROOT

[Install]
WantedBy=multi-user.target
EOF
ok "unit written to /etc/systemd/system/${SERVICE_NAME}.service"

systemctl daemon-reload
systemctl enable "$SERVICE_NAME" >/dev/null
systemctl restart "$SERVICE_NAME"
ok "service enabled and started"

if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
  ufw allow "$PORT/tcp" >/dev/null && ok "ufw now allows TCP $PORT"
fi

step "Waiting for GrotFoxy to answer"
for _ in $(seq 1 30); do
  if curl -fsS "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1; then
    ok "GrotFoxy is responding"
    break
  fi
  sleep 1
done

echo
echo "  GrotFoxy is installed."
echo
echo "  On this machine:  http://localhost:$PORT"
for address in $(hostname -I 2>/dev/null || true); do
  echo "  From your phone:  http://$address:$PORT"
done
echo
echo "  Logs:    journalctl -u $SERVICE_NAME -f"
echo "  Restart: sudo systemctl restart $SERVICE_NAME"
echo
